parameters:
#    ance_star.example.class: Ance\StarBundle\Example

services:
#    ance_star.example:
#        class: %ance_star.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
